---@meta

---@class NvimCreateUserCommandCallbackOpts
---@field name string command name
---@field args string The args passed to the command, if any
---@field fargs string[] The args split by unescaped whitespace (if any)
---@field bang boolean "true" if the command was executed with a ! modifier
---@field line1 integer Starting line of the command range
---@field line2 integer Final line of the command range
---@field range 0|1|2 The number of items in the command range
---@field count integer any count supplied
---@field reg string optional register, if specified
---@field mods string command modifiers, if any
---@field smods table command modifiers in structured format
