---@meta

---@alias VimMode
---|'"n"'         # Normal
---|'"no"'        # Operator-pending
---|'"nov"'       # Operator-pending (forced charwise |o_v|)
---|'"noV"'       # Operator-pending (forced linewise |o_V|)
---|'"no"'      # Operator-pending (forced blockwise |o_CTRL-V|) CTRL-V is one character
---|'"niI"'       # Normal using |i_CTRL-O| in |Insert-mode|
---|'"niR"'       # Normal using |i_CTRL-O| in |Replace-mode|
---|'"niV"'       # Normal using |i_CTRL-O| in |Virtual-Replace-mode|
---|'"nt"'        # Normal in |terminal-emulator| (insert goes to Terminal mode)
---|'"ntT"'       # Normal using |t_CTRL-\_CTRL-O| in |Terminal-mode|
---|'"v"'         # Visual by character
---|'"vs"'				# Visual by character using |v_CTRL-O| in Select mode
---|'"V"'				  # Visual by line
---|'"Vs"'				# Visual by line using |v_CTRL-O| in Select mode
---|'""'				# Visual blockwise
---|'"s"'				# Visual blockwise using |v_CTRL-O| in Select mode
---|'"s"'				  # Select by character
---|'"S"'				  # Select by line
---|'""'				# Select blockwise
---|'"i"'				  # Insert
---|'"ic"'				# Insert mode completion |compl-generic|
---|'"ix"'				# Insert mode |i_CTRL-X| completion
---|'"R"'				  # Replace |R|
---|'"Rc"'				# Replace mode completion |compl-generic|
---|'"Rx"'				# Replace mode |i_CTRL-X| completion
---|'"Rv"'				# Virtual Replace |gR|
---|'"Rvc"'				# Virtual Replace mode completion |compl-generic|
---|'"Rvx"'				# Virtual Replace mode |i_CTRL-X| completion
---|'"c"'				  # Command-line editing
---|'"cv"'				# Vim Ex mode |gQ|
---|'"r"'				  # Hit-enter prompt
---|'"rm"'				# The -- more -- prompt
---|'"r?"'				# A |:confirm| query of some sort
---|'"!"'				  # Shell or external command is executing
---|'"t"'				  # Terminal mode: keys go to the job

---@alias VimKeymapMode
---|'"nvo"'
---|'"n"'
---|'"v"' # Equivalent to "xs"
---|'"x"'
---|'"s"'
---|'"o"' 
---|'"ic"'
---|'"i"'
---|'"l"'
---|'"m"'
---|'"c"'
---|'"t"'
